# -*- coding: utf-8 -*-
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
DATA_DIR.mkdir(exist_ok=True)

import json

BYE = {}
for wk, teams in {
    5: ["KC","CAR"],
    6: ["CIN","DET","MIA","MIN"],
    7: ["BUF","JAX","LAC","WSH"],
    8: ["HOU","NO","NYG","SF"],
    9: ["PIT","TEN"],
    10:["CHI","DEN","PHI","TB"],
    11:["ATL","CLE","GB","LAR","NE","SEA"],
    13:["BAL","IND","LV","NYJ"],
    14:["ARI","DAL"],
}.items():
    for t in teams:
        BYE[t] = wk

# rank, name, pos, team, grade, note
# grades: FLOOR / OK / RISK / AVOID / CUFF
P = [
(1,"Jahmyr Gibbs","RB","DET","FLOOR","Elite volume plus receiving work. The safest weekly floor on the board."),
(2,"Jaxon Smith-Njigba","WR","SEA","FLOOR","Massive target share. Exactly the boring consistency this format wants."),
(3,"Ja'Marr Chase","WR","CIN","FLOOR","Target hog on a pass-heavy offense."),
(4,"Bijan Robinson","RB","ATL","FLOOR","Three-down back, catches passes. Floor and ceiling both elite."),
(5,"Puka Nacua","WR","LAR","OK","Groin soreness in camp — minor, but monitor. Otherwise a target monster."),
(6,"Justin Jefferson","WR","MIN","FLOOR","Best pure receiver alive. Volume never dips."),
(7,"Jonathan Taylor","RB","IND","FLOOR","Workhorse carries. Slightly TD-dependent but volume carries him."),
(8,"Amon-Ra St. Brown","WR","DET","FLOOR","The definition of a PPR floor. 8+ targets every single week."),
(9,"James Cook III","RB","BUF","OK","Great offense, but shares goal-line work. Slightly TD-volatile."),
(10,"CeeDee Lamb","WR","DAL","FLOOR","Alpha target share."),
(11,"De'Von Achane","RB","MIA","OK","Explosive and catches passes; small frame, some week-to-week swing."),
(12,"Nico Collins","WR","HOU","FLOOR","Big target share, reliable."),
(13,"A.J. Brown","WR","NE","RISK","New offense in 2026. Talent is elite, but changing teams adds uncertainty."),
(14,"Ashton Jeanty","RB","LV","OK","True workhorse role. Offense quality is the question."),
(15,"George Pickens","WR","DAL","RISK","Boom-bust profile. Big weeks and quiet weeks — dangerous here."),
(16,"Emeka Egbuka","WR","TB","OK","Minor toe issue in camp, not serious. Good volume."),
(17,"Trey McBride","TE","ARI","FLOOR","TE1 with WR-level targets. Locks down the scarcest position."),
(18,"Omarion Hampton","RB","LAC","OK","Lead back with real volume."),
(19,"Chris Olave","WR","NO","OK","Good target share; some concussion history in his past."),
(20,"Drake London","WR","ATL","FLOOR","Primary option, high target volume. Textbook guillotine WR."),
(21,"Saquon Barkley","RB","PHI","RISK","Age-29 running back. Production cliff risk plus injury history."),
(22,"DeVonta Smith","WR","PHI","OK","Steady but shares targets."),
(23,"Brock Bowers","TE","LV","FLOOR","Elite target volume at a scarce position."),
(24,"Christian McCaffrey","RB","SF","AVOID","Extensive injury history. Enormous talent, but a single miss can end your season."),
(25,"Josh Allen","QB","BUF","FLOOR","Rushing floor makes him nearly zero-proof. Best QB for this format."),
(26,"Garrett Wilson","WR","NYJ","FLOOR","Target hog even on a mediocre offense — that's what you want."),
(27,"Chase Brown","RB","CIN","OK","Lead back on a good offense."),
(28,"Zay Flowers","WR","BAL","OK","Solid volume."),
(29,"Rashee Rice","WR","KC","OK","High-volume slot role."),
(30,"Derrick Henry","RB","BAL","RISK","Volume is real but he's old for the position and TD-dependent."),
(31,"Lamar Jackson","QB","BAL","FLOOR","Rushing floor. Very hard to have a zero week."),
(32,"Joe Burrow","QB","CIN","OK","Elite passing volume, no rushing floor."),
(33,"Colston Loveland","TE","CHI","OK","Rising target share at a thin position."),
(34,"Breece Hall","RB","NYJ","OK","Receiving work gives him a PPR floor."),
(35,"Tetairoa McMillan","WR","CAR","OK","Primary target on a weak offense — volume is there."),
(36,"Kyren Williams","RB","LAR","FLOOR","Enormous touch share. Boring, consistent, exactly right."),
(37,"Jaylen Waddle","WR","DEN","OK","Leg strain in camp, expected fine. New offense."),
(38,"Kenneth Walker III","RB","KC","OK","New team, good offense. Watch the committee split."),
(39,"Drake Maye","QB","NE","OK","Ascending passer with some rushing."),
(40,"Tee Higgins","WR","CIN","OK","Strong WR2 with red-zone work."),
(41,"Javonte Williams","RB","DAL","OK","Lead role, decent volume."),
(42,"Ladd McConkey","WR","LAC","FLOOR","Consistent underneath target volume. Great PPR floor."),
(43,"Jeremiyah Love","RB","ARI","RISK","Rookie. Talent is real, role may take time. Rookies are risky in this format."),
(44,"Terry McLaurin","WR","WSH","OK","Reliable target share."),
(45,"Malik Nabers","WR","NYG","RISK","Coming off a torn ACL. On track for Week 1, but could miss 1-2 games."),
(46,"Davante Adams","WR","LAR","RISK","Age 32+. Still productive but the cliff is real for WRs at this age."),
(47,"Cam Skattebo","RB","NYG","OK","Volume and short-yardage work."),
(48,"Mike Evans","WR","SF","RISK","New team at an advanced age. TD-dependent profile."),
(49,"Luther Burden III","WR","CHI","RISK","Groin injury, likely misses preseason. Week 1 uncertain."),
(50,"Josh Jacobs","RB","GB","OK","Workhorse touches, some age concern."),
(51,"Jameson Williams","WR","DET","RISK","Deep-threat profile. Boom-bust — the 3-point weeks will come."),
(52,"DJ Moore","WR","BUF","OK","New offense but a proven target earner."),
(53,"Travis Etienne Jr.","RB","NO","OK","Receiving work helps the PPR floor."),
(54,"Jalen Hurts","QB","PHI","FLOOR","Rushing TDs give him a very high weekly floor."),
(55,"Marvin Harrison Jr.","WR","ARI","OK","Talent is there; consistency has been the question."),
(56,"David Montgomery","RB","HOU","FLOOR","Boring, high-volume, goal-line work. Ideal guillotine back."),
(57,"Tyler Warren","TE","IND","OK","Growing target share at a scarce position."),
(58,"Quinshon Judkins","RB","CLE","OK","Lead back, weak offense."),
(59,"Caleb Williams","QB","CHI","OK","Rushing upside."),
(60,"Carnell Tate","WR","TEN","RISK","Young receiver, developing role."),
(61,"TreVeyon Henderson","RB","NE","OK","Explosive with receiving work."),
(62,"Christian Watson","WR","GB","RISK","Injury history and a boom-bust deep role. Fade in this format."),
(63,"Jayden Daniels","QB","WSH","FLOOR","Rushing floor. Excellent value if he falls."),
(64,"Rome Odunze","WR","CHI","OK","Gains value while Burden is hurt."),
(65,"D'Andre Swift","RB","CHI","OK","Receiving work gives PPR floor."),
(66,"Tucker Kraft","TE","GB","RISK","Coming off a torn ACL, working toward Week 1. Real miss risk."),
(67,"Bucky Irving","RB","TB","OK","Efficient with receiving work."),
(68,"DK Metcalf","WR","PIT","RISK","Boom-bust. Great some weeks, invisible others."),
(69,"Brian Thomas Jr.","WR","JAX","OK","High target share."),
(70,"Chuba Hubbard","RB","CAR","RISK","Hamstring, week-to-week. Hamstrings recur. Discount him."),
(71,"Dak Prescott","QB","DAL","OK","Good passing volume, no rushing."),
(72,"Courtland Sutton","WR","DEN","OK","Red-zone role, decent floor."),
(73,"Tony Pollard","RB","TEN","OK","Volume back on a weak offense."),
(74,"Kyle Pitts Sr.","TE","ATL","RISK","Perennially inconsistent. Talented but a floor risk at TE."),
(75,"Rico Dowdle","RB","PIT","OK","Lead role."),
(76,"Michael Pittman Jr.","WR","PIT","OK","Possession receiver, decent PPR floor."),
(77,"Bhayshul Tuten","RB","JAX","RISK","Committee risk."),
(78,"Trevor Lawrence","QB","JAX","OK","Streamable starter."),
(79,"Jadarian Price","RB","SEA","RISK","Rookie, unclear role."),
(80,"Alec Pierce","WR","IND","RISK","Deep threat, boom-bust. Ankle issue in camp."),
(81,"Jaylen Warren","RB","PIT","CUFF","Receiving work; good handcuff value."),
(82,"Chris Godwin Jr.","WR","TB","OK","Slot volume when healthy."),
(83,"Michael Wilson","WR","ARI","OK","Steady secondary target."),
(84,"Travis Kelce","TE","KC","RISK","Age has caught up. Rankings vary wildly on him (84 to 129)."),
(85,"RJ Harvey","RB","DEN","OK","Committee back with upside."),
(86,"Harold Fannin Jr.","TE","CLE","OK","Target volume at a thin position."),
(87,"Jordyn Tyson","WR","NO","RISK","Hamstring in camp — second one on the same leg. Monitor closely."),
(88,"Kenny Gainwell","RB","TB","FLOOR","85 targets last season, 5th most among RBs. Pure PPR floor play — a classic guillotine target."),
(89,"Parker Washington","WR","JAX","OK",""),
(90,"Wan'Dale Robinson","WR","TEN","FLOOR","High-volume underneath receiver. Low ceiling, very steady floor."),
(91,"Jaxson Dart","QB","NYG","RISK","Young QB, volatile."),
(92,"Rhamondre Stevenson","RB","NE","OK",""),
(93,"Jakobi Meyers","WR","JAX","OK","Reliable target earner."),
(94,"Sam LaPorta","TE","DET","OK","Talented but target share fluctuates."),
(95,"Aaron Jones Sr.","RB","MIN","AVOID","19 career injuries and age 30+. Exactly the profile to avoid here."),
(96,"Makai Lemon","WR","PHI","RISK","Rookie."),
(97,"Isaiah Likely","TE","NYG","OK","New team, starting TE role."),
(98,"Patrick Mahomes II","QB","KC","OK","Safe passing floor, limited rushing."),
(99,"J.K. Dobbins","RB","DEN","RISK","Long injury history."),
(100,"Ricky Pearsall","WR","SF","AVOID","OUT FOR THE 2026 SEASON — PCL surgery. Do not draft."),
(101,"Kyle Monangai","RB","CHI","OK",""),
(102,"Matthew Stafford","QB","LAR","OK",""),
(103,"Kyler Murray","QB","MIN","OK","Rushing floor helps."),
(104,"Rachaad White","RB","WAS","OK","Receiving work."),
(105,"Matthew Golden","WR","GB","OK",""),
(106,"Jared Goff","QB","DET","OK","Good offense, no rushing."),
(107,"Bo Nix","QB","DEN","OK","Some rushing floor."),
(108,"Stefon Diggs","WR","WSH","RISK","Age and injury history."),
(109,"Jordan Mason","RB","MIN","CUFF",""),
(110,"Xavier Worthy","WR","KC","RISK","Boom-bust speed profile."),
(111,"Jordan Love","QB","GB","OK",""),
(112,"Jayden Higgins","WR","HOU","OK",""),
(113,"Baker Mayfield","QB","TB","OK",""),
(114,"Jonathon Brooks","RB","CAR","RISK","Gains value with Hubbard hurt, but coming off major knee injury. High variance."),
(115,"KC Concepcion","WR","CLE","RISK",""),
(116,"Tyler Shough","QB","NO","RISK",""),
(117,"Dalton Kincaid","TE","BUF","OK",""),
(118,"Jacory Croskey-Merritt","RB","WAS","OK",""),
(119,"George Kittle","TE","SF","AVOID","Achilles, on PUP — out at least 4 weeks. 18 career injuries. Do not draft."),
(120,"Mark Andrews","TE","BAL","OK",""),
(121,"Jalen Coker","WR","CAR","OK",""),
(122,"Chris Rodriguez Jr.","RB","JAX","OK",""),
(123,"Keaton Mitchell","RB","LAC","CUFF",""),
(124,"Malik Willis","QB","MIA","RISK",""),
(125,"Romeo Doubs","WR","NE","OK",""),
(126,"Tyrone Tracy Jr.","RB","NYG","CUFF",""),
(127,"Rashid Shaheed","WR","SEA","RISK","Deep threat, very boom-bust."),
(128,"Khalil Shakir","WR","BUF","FLOOR","Underneath volume. Steady PPR points."),
(129,"Woody Marks","RB","HOU","CUFF","Handcuff to Montgomery."),
(130,"Denzel Boston","WR","CLE","RISK",""),
(131,"Sam Darnold","QB","SEA","OK",""),
(132,"Jake Ferguson","TE","DAL","OK","Decent target share."),
(133,"Jalen McMillan","WR","TB","OK",""),
(134,"De'Zhaun Stribling","WR","SF","OK","Gains real value with Pearsall out for the year."),
(135,"Dallas Goedert","TE","PHI","OK",""),
(136,"Tyjae Spears","RB","TEN","CUFF",""),
(137,"Chig Okonkwo","TE","WAS","OK",""),
(138,"Deebo Samuel","WR","SF","OK","Value up with Pearsall out."),
(139,"C.J. Stroud","QB","HOU","OK",""),
(140,"Jonah Coleman","RB","DEN","OK",""),
(141,"Daniel Jones","QB","IND","OK",""),
(142,"Cam Ward","QB","TEN","RISK",""),
(143,"Dylan Sampson","RB","CLE","CUFF",""),
(144,"Ryan Flournoy","WR","DAL","RISK","Rankings disagree enormously on him (150 to 238)."),
(145,"Zach Charbonnet","RB","SEA","CUFF",""),
(146,"Tank Bigsby","RB","PHI","CUFF",""),
(147,"Aaron Rodgers","QB","PIT","RISK",""),
(148,"Tyler Allgeier","RB","ARI","CUFF",""),
(149,"Omar Cooper Jr.","WR","NYJ","RISK",""),
(150,"Brenton Strange","TE","JAX","OK",""),
(151,"Jalen Nailor","WR","LV","OK",""),
(152,"Oronde Gadsden","TE","LAC","OK",""),
(153,"Isiah Pacheco","RB","DET","OK","Sprained MCL, expected ready Week 1."),
(154,"Bryce Young","QB","CAR","RISK",""),
(155,"MarShawn Lloyd","RB","GB","CUFF",""),
(156,"Tre' Harris","WR","LAC","OK",""),
(157,"Brian Robinson","RB","ATL","CUFF",""),
(158,"Jacoby Brissett","QB","ARI","OK",""),
(159,"Travis Hunter","WR","JAX","RISK","Two-way workload makes his fantasy role hard to project."),
(160,"Jerry Jeudy","WR","CLE","OK",""),
(161,"Alvin Kamara","RB","NO","RISK","Age."),
(162,"Jaydon Blue","RB","DAL","CUFF",""),
(163,"Tre Tucker","WR","LV","RISK",""),
(164,"Hunter Henry","TE","NE","OK",""),
(165,"T.J. Hockenson","TE","MIN","OK",""),
(166,"Juwan Johnson","TE","NO","OK",""),
(167,"Antonio Williams","WR","WSH","OK",""),
(168,"Geno Smith","QB","NYJ","OK",""),
(169,"Adonai Mitchell","WR","NYJ","RISK",""),
(170,"Ray Davis","RB","BUF","CUFF","Handcuff to Cook."),
(171,"Jauan Jennings","WR","MIN","OK",""),
(172,"Emmett Johnson","RB","KC","CUFF",""),
(173,"Kenyon Sadiq","TE","NYJ","RISK","Hernia surgery setback."),
(174,"Mike Washington Jr.","RB","LV","CUFF","Handcuff to Jeanty."),
(175,"Dalton Schultz","TE","HOU","OK",""),
(176,"Braelon Allen","RB","NYJ","CUFF","Handcuff to Breece Hall."),
(177,"Demond Claiborne","RB","MIN","CUFF",""),
(178,"Kimani Vidal","RB","LAC","CUFF","Handcuff to Hampton."),
(179,"Sean Tucker","RB","TB","CUFF",""),
(180,"Gunnar Helm","TE","TEN","OK",""),
(181,"Isaac TeSlaa","WR","DET","OK",""),
(182,"Terrance Ferguson","TE","LAR","OK",""),
(183,"Kaytron Allen","RB","WSH","CUFF",""),
(184,"Kaelon Black","RB","SF","CUFF",""),
(185,"Calvin Ridley","WR","TEN","RISK","Rankings vary widely (143 to 192)."),
(186,"AJ Barner","TE","SEA","OK",""),
(187,"Nicholas Singleton","RB","TEN","CUFF",""),
(188,"Zachariah Branch","WR","ATL","RISK",""),
(189,"Rashod Bateman","WR","BAL","OK",""),
(190,"James Conner","RB","ARI","RISK","Age and injury history."),
(191,"Malik Washington","WR","MIA","OK",""),
(192,"Tua Tagovailoa","QB","ATL","RISK","New team, concussion history."),
(193,"Greg Dulcich","TE","MIA","OK",""),
(194,"Germie Bernard","WR","PIT","OK",""),
(195,"Ja'Kobi Lane","WR","BAL","OK",""),
(196,"Pat Bryant","WR","DEN","OK",""),
(197,"Dontayvion Wicks","WR","PHI","OK",""),
(198,"Jordan James","RB","SF","CUFF",""),
(199,"Pat Freiermuth","TE","PIT","OK",""),
(200,"Tank Dell","WR","HOU","RISK","Injury history."),
(201,"Cade Otton","TE","TB","OK",""),
(202,"Kayshon Boutte","WR","NE","OK",""),
(203,"Jaylen Wright","RB","MIA","CUFF",""),
(204,"Mike Gesicki","TE","CIN","OK",""),
(205,"Cooper Kupp","WR","SEA","RISK","Age and injury history. Rankings vary (186 to 220)."),
(206,"Darnell Mooney","WR","NYG","OK",""),
(207,"Jaylin Noel","WR","HOU","OK",""),
(208,"Troy Franklin","WR","DEN","OK",""),
(209,"Justice Hill","RB","BAL","CUFF",""),
(210,"Tory Horton","WR","SEA","OK",""),
(211,"Devaughn Vele","WR","NO","OK",""),
(212,"DJ Giddens","RB","IND","CUFF","Handcuff to Jonathan Taylor — high-value cuff."),
(213,"Darius Slayton","WR","NYG","OK",""),
(214,"Evan Engram","TE","DEN","OK",""),
(215,"David Njoku","TE","LAC","OK",""),
(216,"Trey Benson","RB","ARI","CUFF",""),
(217,"Brandon Aiyuk","WR","SF","RISK","Coming back from major injury."),
(218,"Theo Johnson","TE","NYG","OK",""),
(219,"Andrei Iosivas","WR","CIN","OK",""),
(220,"Jalen Tolbert","WR","MIA","OK",""),
]

FA = [
 ("Keenan Allen","WR","Unsigned free agent as of mid-August. Do not draft until he signs."),
 ("Tyreek Hill","WR","Unsigned free agent as of mid-August. Do not draft until he signs."),
]

rows = []
for r, name, pos, team, grade, note in P:
    rows.append({
        "r": r, "n": name, "p": pos, "t": team,
        "b": BYE.get(team, 0), "g": grade, "note": note,
        "rd": (r + 17) // 18,
    })

posrank = {}
for row in rows:
    posrank[row["p"]] = posrank.get(row["p"], 0) + 1
    row["pr"] = f'{row["p"]}{posrank[row["p"]]}'

print(json.dumps(rows)[:400])
print("total", len(rows))
with open(str(DATA_DIR / "board.json"),"w") as f:
    json.dump({"players": rows, "fa": FA}, f)
